import { Link, createFileRoute, useNavigate } from '@tanstack/react-router'
import { AlertTriangle, ExternalLink, RefreshCcw, ShieldCheck, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { PageHeader } from '@/components/PageHeader'
import { useAppState } from '@/lib/store'
import { signOut } from '@/lib/auth'

export const Route = createFileRoute('/app/settings')({ component: SettingsScreen })
type Subscription = { status: 'not_started' | 'trialing' | 'active' | 'past_due' | 'canceled'; trialStartedAt: string | null; trialEndsAt: string | null; subscriptionStartedAt: string | null; paymentDate: string | null; renewalDate: string | null; cancelAtPeriodEnd: boolean }

function SettingsScreen() {
  const { user } = useAppState(); const navigate = useNavigate()
  const [subscription, setSubscription] = useState<Subscription | null>(null); const [manageUrl, setManageUrl] = useState<string | null>(null); const [unsubscribed, setUnsubscribed] = useState(false); const [deleting, setDeleting] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (user) setUnsubscribed(window.localStorage.getItem(`proteus:communications:${user.id}`) === 'unsubscribed'); void Promise.all([fetch('/api/subscription', { credentials: 'same-origin', cache: 'no-store' }).then(async (r) => r.ok ? (await r.json()).subscription as Subscription : null), fetch('/api/billing/manage', { credentials: 'same-origin', cache: 'no-store' }).then(async (r) => r.ok ? (await r.json()).manageUrl as string | null : null)]).then(([s, url]) => { setSubscription(s); setManageUrl(url) }) }, [user])
  const deleteAccount = async () => { if (!window.confirm('Delete your Proteus account and browser-saved plan data? This cannot be undone.')) return; setDeleting(true); setError(null); try { const response = await fetch('/api/account/delete', { method: 'DELETE', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ confirmation: 'DELETE' }) }); const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(body.error ?? `Account deletion failed (${response.status}).`); localStorage.removeItem(`proteus:plan:v3:${user?.id}`); await signOut(); navigate({ to: '/' }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Your account could not be deleted.') } finally { setDeleting(false) } }
  const hasBilling = subscription && ['trialing', 'active', 'past_due'].includes(subscription.status)
  return <div>
    <PageHeader eyebrow="Account controls" title="Account & subscription details">Manage your account, privacy choices, billing timeline, and cancellation without hidden steps.</PageHeader>
    <div className="grid gap-6 lg:grid-cols-2">
      <section className="panel p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 h-5 w-5 text-volt-2" /><div><h2 className="font-display text-lg font-bold text-white">Privacy & communication</h2><p className="mt-2 text-sm leading-relaxed text-white">Proteus does not send SMS, push notifications, or marketing messages. We do not run advertising analytics or send your health inputs to tracking vendors.</p></div></div><div className="mt-5 flex flex-wrap items-center gap-3">{unsubscribed ? <span className="rounded-full border border-emerald-200/30 bg-emerald-200/10 px-3 py-1.5 text-xs font-semibold text-white">Unsubscribed from optional communications</span> : <button onClick={() => { setUnsubscribed(true); if (user) window.localStorage.setItem(`proteus:communications:${user.id}`, 'unsubscribed') }} className="rounded-full border border-white/30 px-3 py-1.5 text-xs font-semibold text-white hover:border-volt-2">Unsubscribe from optional communications</button>}<Link to="/privacy" className="text-sm font-semibold text-volt-2 hover:text-white">Read the full Privacy Policy →</Link></div><button type="button" className="seg mt-5 inline-flex items-center gap-2" onClick={() => window.dispatchEvent(new Event('proteus:new-monthly-flow'))}><RefreshCcw className="h-4 w-4 text-volt-2" /> Start New Monthly Flow</button></section>
      <section className="panel p-6"><div className="flex items-start gap-3"><ExternalLink className="mt-1 h-5 w-5 text-volt-2" /><div><h2 className="font-display text-lg font-bold text-white">Subscription cancellation</h2><p className="mt-2 text-sm leading-relaxed text-white">{subscription ? `Status: ${subscription.status.replace('_', ' ')}${subscription.cancelAtPeriodEnd ? ' · cancels at renewal' : ''}.` : 'Checking your current subscription status…'}</p></div></div>{hasBilling && manageUrl ? <a className="btn-glow btn-sm mt-5 inline-flex" href={manageUrl} target="_blank" rel="noreferrer">Open Whop billing controls <ExternalLink className="h-4 w-4" /></a> : hasBilling ? <p className="mt-5 rounded-xl border border-amber-200/20 bg-amber-200/10 p-3 text-xs leading-relaxed text-white">Whop billing controls are not configured on this Preview. Ask support for the secure cancellation link; Proteus will only mark cancellation after Whop sends its signed confirmation.</p> : <p className="mt-5 text-xs text-white">There is no active recurring subscription to cancel.</p>}<Link to="/refund" className="mt-4 block text-sm font-semibold text-volt-2 hover:text-white">See cancellation and refund terms →</Link></section>
      <section className="panel p-6 lg:col-span-2"><h2 className="font-display text-lg font-bold text-white">Plan timeline & billing details</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><InfoRow label="Current status" value={subscription?.status?.replace('_', ' ') ?? 'Not started'} /><InfoRow label="Started" value={subscription?.subscriptionStartedAt ?? subscription?.trialStartedAt ?? 'Not started'} /><InfoRow label="Renewal" value={subscription?.renewalDate ?? subscription?.trialEndsAt ?? 'Not scheduled'} /><InfoRow label="Payment / end" value={subscription?.paymentDate ?? (subscription?.cancelAtPeriodEnd ? 'Cancels at renewal' : 'No end date')} /></div></section>
      <section className="panel border-rose-200/20 p-6 lg:col-span-2"><div className="flex items-start gap-3"><Trash2 className="mt-1 h-5 w-5 text-rose-200" /><div><h2 className="font-display text-lg font-bold text-white">Delete account</h2><p className="mt-2 text-sm leading-relaxed text-white">This removes your Proteus account and browser-saved plan data. Billing must be canceled with Whop first; we never silently cancel a provider subscription while deleting an account.</p></div></div>{error && <p role="alert" className="mt-4 rounded-xl border border-rose-200/20 bg-rose-200/10 p-3 text-sm text-white"><AlertTriangle className="mr-2 inline h-4 w-4" />{error}</p>}<button onClick={() => void deleteAccount()} disabled={deleting} className="mt-5 inline-flex items-center gap-2 rounded-full border border-rose-200/50 px-4 py-2 text-sm font-semibold text-white hover:bg-rose-200/10 disabled:opacity-50"><Trash2 className="h-4 w-4" />{deleting ? 'Deleting…' : 'Delete my account'}</button></section>
      <section className="panel border-volt/20 p-6 lg:col-span-2"><h2 className="font-display text-lg font-bold text-white">Wellness disclaimer</h2><p className="mt-2 text-sm leading-relaxed text-white">Proteus is an AI-powered tracking and educational tool and does NOT replace professional medical or nutritional advice. Always consult with qualified healthcare professionals for medical or dietary decisions.</p><Link to="/privacy" className="mt-3 inline-block text-sm font-semibold text-volt-2 hover:text-white">Review privacy and data handling →</Link></section>
    </div>
  </div>
}
function InfoRow({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/15 bg-white/[0.04] p-3"><p className="text-xs uppercase tracking-wider text-white">{label}</p><p className="mt-1 font-semibold text-white">{value}</p></div> }
