/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiProfileRouteImport } from './routes/api.profile'
import { Route as ApiSubscriptionRouteImport } from './routes/api.subscription'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCheckInRouteImport } from './routes/app.check-in'
import { Route as AppFitnessRouteImport } from './routes/app.fitness'
import { Route as AppMealScannerRouteImport } from './routes/app.meal-scanner'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppProteinRouteImport } from './routes/app.protein'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as ApiAccountDeleteRouteImport } from './routes/api.account.delete'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin.login'
import { Route as ApiAdminSubscriptionsRouteImport } from './routes/api.admin.subscriptions'
import { Route as ApiAuthDevRouteImport } from './routes/api.auth.dev'
import { Route as ApiAuthGoogleRouteImport } from './routes/api.auth.google'
import { Route as ApiAuthPasswordRouteImport } from './routes/api.auth.password'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiAuthVerifyEmailRouteImport } from './routes/api.auth.verify-email'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api.billing.checkout'
import { Route as ApiBillingManageRouteImport } from './routes/api.billing.manage'
import { Route as ApiWebhooksPaymentRouteImport } from './routes/api.webhooks.payment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionRoute = ApiSubscriptionRouteImport.update({
  id: '/api/subscription',
  path: '/api/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckInRoute = AppCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AppRoute,
} as any)
const AppFitnessRoute = AppFitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => AppRoute,
} as any)
const AppMealScannerRoute = AppMealScannerRouteImport.update({
  id: '/meal-scanner',
  path: '/meal-scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppProteinRoute = AppProteinRouteImport.update({
  id: '/protein',
  path: '/protein',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubscriptionsRoute = ApiAdminSubscriptionsRouteImport.update({
  id: '/api/admin/subscriptions',
  path: '/api/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDevRoute = ApiAuthDevRouteImport.update({
  id: '/api/auth/dev',
  path: '/api/auth/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasswordRoute = ApiAuthPasswordRouteImport.update({
  id: '/api/auth/password',
  path: '/api/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyEmailRoute = ApiAuthVerifyEmailRouteImport.update({
  id: '/api/auth/verify-email',
  path: '/api/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingManageRoute = ApiBillingManageRouteImport.update({
  id: '/api/billing/manage',
  path: '/api/billing/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaymentRoute = ApiWebhooksPaymentRouteImport.update({
  id: '/api/webhooks/payment',
  path: '/api/webhooks/payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/app/check-in': typeof AppCheckInRoute
  '/app/fitness': typeof AppFitnessRoute
  '/app/meal-scanner': typeof AppMealScannerRoute
  '/app/plan': typeof AppPlanRoute
  '/app/protein': typeof AppProteinRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/': typeof AppIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/auth/dev': typeof ApiAuthDevRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/manage': typeof ApiBillingManageRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/app/check-in': typeof AppCheckInRoute
  '/app/fitness': typeof AppFitnessRoute
  '/app/meal-scanner': typeof AppMealScannerRoute
  '/app/plan': typeof AppPlanRoute
  '/app/protein': typeof AppProteinRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app': typeof AppIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/auth/dev': typeof ApiAuthDevRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/manage': typeof ApiBillingManageRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/app/check-in': typeof AppCheckInRoute
  '/app/fitness': typeof AppFitnessRoute
  '/app/meal-scanner': typeof AppMealScannerRoute
  '/app/plan': typeof AppPlanRoute
  '/app/protein': typeof AppProteinRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/': typeof AppIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/auth/dev': typeof ApiAuthDevRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/manage': typeof ApiBillingManageRoute
  '/api/webhooks/payment': typeof ApiWebhooksPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/privacy'
    | '/refund'
    | '/support'
    | '/terms'
    | '/api/contact'
    | '/api/profile'
    | '/api/subscription'
    | '/app/check-in'
    | '/app/fitness'
    | '/app/meal-scanner'
    | '/app/plan'
    | '/app/protein'
    | '/app/settings'
    | '/app/support'
    | '/app/'
    | '/api/account/delete'
    | '/api/admin/login'
    | '/api/admin/subscriptions'
    | '/api/auth/dev'
    | '/api/auth/google'
    | '/api/auth/password'
    | '/api/auth/session'
    | '/api/auth/verify-email'
    | '/api/billing/checkout'
    | '/api/billing/manage'
    | '/api/webhooks/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy'
    | '/refund'
    | '/support'
    | '/terms'
    | '/api/contact'
    | '/api/profile'
    | '/api/subscription'
    | '/app/check-in'
    | '/app/fitness'
    | '/app/meal-scanner'
    | '/app/plan'
    | '/app/protein'
    | '/app/settings'
    | '/app/support'
    | '/app'
    | '/api/account/delete'
    | '/api/admin/login'
    | '/api/admin/subscriptions'
    | '/api/auth/dev'
    | '/api/auth/google'
    | '/api/auth/password'
    | '/api/auth/session'
    | '/api/auth/verify-email'
    | '/api/billing/checkout'
    | '/api/billing/manage'
    | '/api/webhooks/payment'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/privacy'
    | '/refund'
    | '/support'
    | '/terms'
    | '/api/contact'
    | '/api/profile'
    | '/api/subscription'
    | '/app/check-in'
    | '/app/fitness'
    | '/app/meal-scanner'
    | '/app/plan'
    | '/app/protein'
    | '/app/settings'
    | '/app/support'
    | '/app/'
    | '/api/account/delete'
    | '/api/admin/login'
    | '/api/admin/subscriptions'
    | '/api/auth/dev'
    | '/api/auth/google'
    | '/api/auth/password'
    | '/api/auth/session'
    | '/api/auth/verify-email'
    | '/api/billing/checkout'
    | '/api/billing/manage'
    | '/api/webhooks/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiSubscriptionRoute: typeof ApiSubscriptionRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminSubscriptionsRoute: typeof ApiAdminSubscriptionsRoute
  ApiAuthDevRoute: typeof ApiAuthDevRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthPasswordRoute: typeof ApiAuthPasswordRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthVerifyEmailRoute: typeof ApiAuthVerifyEmailRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingManageRoute: typeof ApiBillingManageRoute
  ApiWebhooksPaymentRoute: typeof ApiWebhooksPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription': {
      id: '/api/subscription'
      path: '/api/subscription'
      fullPath: '/api/subscription'
      preLoaderRoute: typeof ApiSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/check-in': {
      id: '/app/check-in'
      path: '/check-in'
      fullPath: '/app/check-in'
      preLoaderRoute: typeof AppCheckInRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fitness': {
      id: '/app/fitness'
      path: '/fitness'
      fullPath: '/app/fitness'
      preLoaderRoute: typeof AppFitnessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meal-scanner': {
      id: '/app/meal-scanner'
      path: '/meal-scanner'
      fullPath: '/app/meal-scanner'
      preLoaderRoute: typeof AppMealScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/protein': {
      id: '/app/protein'
      path: '/protein'
      fullPath: '/app/protein'
      preLoaderRoute: typeof AppProteinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/subscriptions': {
      id: '/api/admin/subscriptions'
      path: '/api/admin/subscriptions'
      fullPath: '/api/admin/subscriptions'
      preLoaderRoute: typeof ApiAdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/dev': {
      id: '/api/auth/dev'
      path: '/api/auth/dev'
      fullPath: '/api/auth/dev'
      preLoaderRoute: typeof ApiAuthDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password': {
      id: '/api/auth/password'
      path: '/api/auth/password'
      fullPath: '/api/auth/password'
      preLoaderRoute: typeof ApiAuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-email': {
      id: '/api/auth/verify-email'
      path: '/api/auth/verify-email'
      fullPath: '/api/auth/verify-email'
      preLoaderRoute: typeof ApiAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/manage': {
      id: '/api/billing/manage'
      path: '/api/billing/manage'
      fullPath: '/api/billing/manage'
      preLoaderRoute: typeof ApiBillingManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/payment': {
      id: '/api/webhooks/payment'
      path: '/api/webhooks/payment'
      fullPath: '/api/webhooks/payment'
      preLoaderRoute: typeof ApiWebhooksPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCheckInRoute: typeof AppCheckInRoute
  AppFitnessRoute: typeof AppFitnessRoute
  AppMealScannerRoute: typeof AppMealScannerRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProteinRoute: typeof AppProteinRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckInRoute: AppCheckInRoute,
  AppFitnessRoute: AppFitnessRoute,
  AppMealScannerRoute: AppMealScannerRoute,
  AppPlanRoute: AppPlanRoute,
  AppProteinRoute: AppProteinRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiSubscriptionRoute: ApiSubscriptionRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminSubscriptionsRoute: ApiAdminSubscriptionsRoute,
  ApiAuthDevRoute: ApiAuthDevRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthPasswordRoute: ApiAuthPasswordRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthVerifyEmailRoute: ApiAuthVerifyEmailRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingManageRoute: ApiBillingManageRoute,
  ApiWebhooksPaymentRoute: ApiWebhooksPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
